name = "hax"
version = "0.1.0"
defaultTargets = ["Hax", "CoreModels"]

[[lean_lib]]
name = "Hax"

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "52fd4383f59928749da91ee6455d060b98bd0617"
