name = "hax"
version = "0.3.0"
defaultTargets = ["Hax", "CoreModels"]

[[lean_lib]]
name = "Hax"

[[lean_lib]]
name = "CoreModels"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "ae2f343ec5b07e3bbcf54006081e60860f73d9cb"
