name = "hax"
version = "0.3.3"
defaultTargets = ["Hax", "CoreModels"]

[[lean_lib]]
name = "Hax"

[[lean_lib]]
name = "CoreModels"

# Test module. Deliberately excluded from `defaultTargets` so it is not part of the
# regular build; build it explicitly with `lake build Tests`.
[[lean_lib]]
name = "Tests"

[[require]]
name = "aeneas"
git = { url = "https://github.com/cryspen/aeneas", subDir = "backends/lean" }
rev = "ae2f343ec5b07e3bbcf54006081e60860f73d9cb"
