-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [core_models]: type definitions
import Aeneas
import CoreModels.Command
import CoreModels.Core.TypesPrologue
import CoreModels.RustPrimitives.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace CoreModels.core

/-- [core_models::ptr::alignment::AlignmentEnum]
    Source: 'core-models/src/core/ptr.rs', lines 11:16-16:17
    Visibility: public -/
@[discriminant isize]
inductive ptr.alignment.AlignmentEnum where
| _Align1Shl0 : ptr.alignment.AlignmentEnum
| _Align1Shl1 : ptr.alignment.AlignmentEnum
| _Align1Shl2 : ptr.alignment.AlignmentEnum
| _Align1Shl3 : ptr.alignment.AlignmentEnum
| _Align1Shl4 : ptr.alignment.AlignmentEnum
| _Align1Shl5 : ptr.alignment.AlignmentEnum
| _Align1Shl6 : ptr.alignment.AlignmentEnum
| _Align1Shl7 : ptr.alignment.AlignmentEnum
| _Align1Shl8 : ptr.alignment.AlignmentEnum
| _Align1Shl9 : ptr.alignment.AlignmentEnum
| _Align1Shl10 : ptr.alignment.AlignmentEnum
| _Align1Shl11 : ptr.alignment.AlignmentEnum
| _Align1Shl12 : ptr.alignment.AlignmentEnum
| _Align1Shl13 : ptr.alignment.AlignmentEnum
| _Align1Shl14 : ptr.alignment.AlignmentEnum
| _Align1Shl15 : ptr.alignment.AlignmentEnum
| _Align1Shl16 : ptr.alignment.AlignmentEnum
| _Align1Shl17 : ptr.alignment.AlignmentEnum
| _Align1Shl18 : ptr.alignment.AlignmentEnum
| _Align1Shl19 : ptr.alignment.AlignmentEnum
| _Align1Shl20 : ptr.alignment.AlignmentEnum
| _Align1Shl21 : ptr.alignment.AlignmentEnum
| _Align1Shl22 : ptr.alignment.AlignmentEnum
| _Align1Shl23 : ptr.alignment.AlignmentEnum
| _Align1Shl24 : ptr.alignment.AlignmentEnum
| _Align1Shl25 : ptr.alignment.AlignmentEnum
| _Align1Shl26 : ptr.alignment.AlignmentEnum
| _Align1Shl27 : ptr.alignment.AlignmentEnum
| _Align1Shl28 : ptr.alignment.AlignmentEnum
| _Align1Shl29 : ptr.alignment.AlignmentEnum
| _Align1Shl30 : ptr.alignment.AlignmentEnum
| _Align1Shl31 : ptr.alignment.AlignmentEnum
| _Align1Shl32 : ptr.alignment.AlignmentEnum
| _Align1Shl33 : ptr.alignment.AlignmentEnum
| _Align1Shl34 : ptr.alignment.AlignmentEnum
| _Align1Shl35 : ptr.alignment.AlignmentEnum
| _Align1Shl36 : ptr.alignment.AlignmentEnum
| _Align1Shl37 : ptr.alignment.AlignmentEnum
| _Align1Shl38 : ptr.alignment.AlignmentEnum
| _Align1Shl39 : ptr.alignment.AlignmentEnum
| _Align1Shl40 : ptr.alignment.AlignmentEnum
| _Align1Shl41 : ptr.alignment.AlignmentEnum
| _Align1Shl42 : ptr.alignment.AlignmentEnum
| _Align1Shl43 : ptr.alignment.AlignmentEnum
| _Align1Shl44 : ptr.alignment.AlignmentEnum
| _Align1Shl45 : ptr.alignment.AlignmentEnum
| _Align1Shl46 : ptr.alignment.AlignmentEnum
| _Align1Shl47 : ptr.alignment.AlignmentEnum
| _Align1Shl48 : ptr.alignment.AlignmentEnum
| _Align1Shl49 : ptr.alignment.AlignmentEnum
| _Align1Shl50 : ptr.alignment.AlignmentEnum
| _Align1Shl51 : ptr.alignment.AlignmentEnum
| _Align1Shl52 : ptr.alignment.AlignmentEnum
| _Align1Shl53 : ptr.alignment.AlignmentEnum
| _Align1Shl54 : ptr.alignment.AlignmentEnum
| _Align1Shl55 : ptr.alignment.AlignmentEnum
| _Align1Shl56 : ptr.alignment.AlignmentEnum
| _Align1Shl57 : ptr.alignment.AlignmentEnum
| _Align1Shl58 : ptr.alignment.AlignmentEnum
| _Align1Shl59 : ptr.alignment.AlignmentEnum
| _Align1Shl60 : ptr.alignment.AlignmentEnum
| _Align1Shl61 : ptr.alignment.AlignmentEnum
| _Align1Shl62 : ptr.alignment.AlignmentEnum
| _Align1Shl63 : ptr.alignment.AlignmentEnum

/-- [core_models::ptr::alignment::Alignment]
    Source: 'core-models/src/core/ptr.rs', lines 28:4-28:40
    Visibility: public -/
@[reducible]
def ptr.alignment.Alignment := ptr.alignment.AlignmentEnum

/-- [core_models::alloc::layout::Layout]
    Source: 'core-models/src/core/alloc.rs', lines 11:4-14:5
    Visibility: public -/
structure alloc.layout.Layout where
  size : Std.Usize
  align : ptr.alignment.Alignment

/-- [core_models::alloc::layout::LayoutError]
    Source: 'core-models/src/core/alloc.rs', lines 17:4-17:27
    Visibility: public -/
@[reducible]
def alloc.layout.LayoutError := Unit

/-- [core_models::array::TryFromSliceError]
    Source: 'core-models/src/core/array.rs', lines 4:0-4:29
    Visibility: public -/
@[reducible]
def array.TryFromSliceError := Unit

/-
/-- [core_models::array::Array]
    Source: 'core-models/src/core/array.rs', lines 10:0-10:40 -/
@[reducible]
def array.Array (T : Type) (N : Std.Usize) := Array T N
-/

/-- [core_models::array::{core_models::array::Array<T, N>}::each_ref::closure]
    Source: 'core-models/src/core/array.rs', lines 65:22-65:43 -/
@[reducible]
def array.Array.each_ref.closure (T : Type) (N : Std.Usize) := Array T N

/-
/-- [core_models::option::Option]
    Source: 'core-models/src/core/option.rs', lines 3:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive option.Option (T : Type) where
| Some : T → option.Option T
| None : option.Option T
-/

/-- Trait declaration: [core_models::iter::traits::iterator::Iterator]
    Source: 'core-models/src/core/iter.rs', lines 17:8-21:9
    Visibility: public -/
structure iter.traits.iterator.Iterator (Self : Type) (Self_Item : Type) where
  next : Self → RustM ((option.Option Self_Item) × Self)

/-- Trait declaration: [core_models::iter::traits::collect::IntoIterator]
    Source: 'core-models/src/core/iter.rs', lines 461:8-469:9
    Visibility: public -/
structure iter.traits.collect.IntoIterator (Self : Type) (Self_Item : Type)
  (Self_IntoIter : Type) where
  iteratorIteratorInst : iter.traits.iterator.Iterator Self_IntoIter Self_Item
  into_iter : Self → RustM Self_IntoIter

/-- [core_models::array::iter::IntoIter]
    Source: 'core-models/src/core/array.rs', lines 240:4-240:55
    Visibility: public -/
@[reducible]
def array.iter.IntoIter (T : Type) (N : Std.Usize) :=
  rust_primitives.sequence.Seq T

/-- Trait declaration: [core_models::ops::index::Index]
    Source: 'core-models/src/core/ops.rs', lines 144:4-147:5
    Visibility: public -/
structure ops.index.Index (Self : Type) (Idx : Type) (Self_Output : Type) where
  index : Self → Idx → RustM Self_Output

/-- Trait declaration: [core_models::ops::index::IndexMut]
    Source: 'core-models/src/core/ops.rs', lines 155:4-157:5
    Visibility: public -/
structure ops.index.IndexMut (Self : Type) (Idx : Type) (Self_Clause0_Output :
  Type) where
  IndexInst : ops.index.Index Self Idx Self_Clause0_Output
  index_mut : Self → Idx → RustM (Self_Clause0_Output ×
    (Self_Clause0_Output → Self))

/-- Trait declaration: [core_models::clone::Clone]
    Source: 'core-models/src/core/clone.rs', lines 13:0-25:1
    Visibility: public -/
structure clone.Clone (Self : Type) where
  clone : Self → RustM Self
  clone_from : Self → Self → RustM Self

/-- Trait declaration: [core_models::cmp::PartialEq]
    Source: 'core-models/src/core/cmp.rs', lines 5:0-23:1
    Visibility: public -/
structure cmp.PartialEq (Self : Type) (Rhs : Type) where
  eq : Self → Rhs → RustM Bool
  ne : Self → Rhs → RustM Bool

/-- Trait declaration: [core_models::default::Default]
    Source: 'core-models/src/core/default.rs', lines 3:0-7:1
    Visibility: public -/
structure default.Default (Self : Type) where
  default : RustM Self

/-- [core_models::array::{impl core_models::default::Default for [T; N]}::default::closure]
    Source: 'core-models/src/core/array.rs', lines 210:22-210:68 -/
@[reducible]
def array.DefaultArray.default.closure (T : Type) (N : Std.Usize) := Unit

/-
/-- [core_models::result::Result]
    Source: 'core-models/src/core/result.rs', lines 3:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive result.Result (T : Type) (E : Type) where
| Ok : T → result.Result T E
| Err : E → result.Result T E
-/

/-- [core_models::fmt::Formatter]
    Source: 'core-models/src/core/fmt.rs', lines 10:0-10:21
    Visibility: public -/
@[reducible]
def fmt.Formatter := Unit

/-- [core_models::fmt::Error]
    Source: 'core-models/src/core/fmt.rs', lines 4:0-4:17
    Visibility: public -/
@[reducible]
def fmt.Error := Unit

/-- Trait declaration: [core_models::fmt::Debug]
    Source: 'core-models/src/core/fmt.rs', lines 85:0-91:1
    Visibility: public -/
structure fmt.Debug (Self : Type) where
  fmt : Self → fmt.Formatter → RustM ((result.Result Unit fmt.Error) ×
    fmt.Formatter)

/-- Trait declaration: [core_models::convert::AsRef]
    Source: 'core-models/src/core/convert.rs', lines 83:0-87:1
    Visibility: public -/
structure convert.AsRef (Self : Type) (T : Type) where
  as_ref : Self → RustM T

/-- Trait declaration: [core_models::borrow::Borrow]
    Source: 'core-models/src/core/borrow.rs', lines 2:0-5:1 -/
structure borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → RustM Borrowed

/-- Trait declaration: [core_models::cmp::Eq]
    Source: 'core-models/src/core/cmp.rs', lines 26:0-26:32
    Visibility: public -/
structure cmp.Eq (Self : Type) where
  PartialEqInst : cmp.PartialEq Self Self

/-
/-- [core_models::cmp::Ordering]
    Source: 'core-models/src/core/cmp.rs', lines 30:0-37:1
    Visibility: public -/
@[discriminant isize [-1,0,1]]
inductive cmp.Ordering where
| Less : cmp.Ordering
| Equal : cmp.Ordering
| Greater : cmp.Ordering
-/

/-- Trait declaration: [core_models::cmp::PartialOrd]
    Source: 'core-models/src/core/cmp.rs', lines 41:0-77:1
    Visibility: public -/
structure cmp.PartialOrd (Self : Type) (Rhs : Type) where
  PartialEqInst : cmp.PartialEq Self Rhs
  partial_cmp : Self → Rhs → RustM (option.Option cmp.Ordering)
  lt : Self → Rhs → RustM Bool
  le : Self → Rhs → RustM Bool
  gt : Self → Rhs → RustM Bool
  ge : Self → Rhs → RustM Bool

/-- Trait declaration: [core_models::cmp::Neq]
    Source: 'core-models/src/core/cmp.rs', lines 80:0-83:1 -/
structure cmp.Neq (Self : Type) (Rhs : Type) where
  neq : Self → Rhs → RustM Bool

/-- Trait declaration: [core_models::cmp::Ord]
    Source: 'core-models/src/core/cmp.rs', lines 151:0-155:1
    Visibility: public -/
structure cmp.Ord (Self : Type) where
  EqInst : cmp.Eq Self
  PartialOrdInst : cmp.PartialOrd Self Self
  cmp : Self → Self → RustM cmp.Ordering

/-- [core_models::cmp::Reverse]
    Source: 'core-models/src/core/cmp.rs', lines 174:0-174:29
    Visibility: public -/
@[reducible]
def cmp.Reverse (T : Type) := T

/-- Trait declaration: [core_models::convert::TryInto]
    Source: 'core-models/src/core/convert.rs', lines 5:0-10:1 -/
structure convert.TryInto (Self : Type) (T : Type) (Self_Error : Type) where
  try_into : Self → RustM (result.Result T Self_Error)

/-- Trait declaration: [core_models::convert::Into]
    Source: 'core-models/src/core/convert.rs', lines 14:0-18:1 -/
structure convert.Into (Self : Type) (T : Type) where
  into : Self → RustM T

/-- Trait declaration: [core_models::convert::From]
    Source: 'core-models/src/core/convert.rs', lines 22:0-26:1
    Visibility: public -/
structure convert.From (Self : Type) (T : Type) where
  «from» : T → RustM Self

/-- Trait declaration: [core_models::convert::TryFrom]
    Source: 'core-models/src/core/convert.rs', lines 30:0-35:1
    Visibility: public -/
structure convert.TryFrom (Self : Type) (T : Type) (Self_Error : Type) where
  try_from : T → RustM (result.Result Self Self_Error)

/-- [core_models::convert::Infallible]
    Source: 'core-models/src/core/convert.rs', lines 44:0-44:22
    Visibility: public -/
@[reducible]
def convert.Infallible := Unit

/-- [core_models::convert::{impl core_models::convert::TryFrom<&'_0 [T], core_models::array::TryFromSliceError> for [T; N]}::try_from::closure]
    Source: 'core-models/src/core/convert.rs', lines 59:61-61:13 -/
@[reducible]
def convert.TryFromArrayShared0SliceTryFromSliceError.try_from.closure (T :
  Type) (N : Std.Usize) :=
  Slice T

/-- [core_models::num::error::TryFromIntError]
    Source: 'core-models/src/core/num/error.rs', lines 6:0-6:42
    Visibility: public -/
@[reducible]
def num.error.TryFromIntError := Unit

/-- Trait declaration: [core_models::fmt::Display]
    Source: 'core-models/src/core/fmt.rs', lines 79:0-82:1
    Visibility: public -/
structure fmt.Display (Self : Type) where
  fmt : Self → fmt.Formatter → RustM ((result.Result Unit fmt.Error) ×
    fmt.Formatter)

/-- Trait declaration: [core_models::error::Error]
    Source: 'core-models/src/core/error.rs', lines 4:0-4:35
    Visibility: public -/
structure error.Error (Self : Type) where
  fmtDisplayInst : fmt.Display Self
  fmtDebugInst : fmt.Debug Self

/-- [core_models::f32::f32]
    Source: 'core-models/src/core/f32.rs', lines 6:0-6:11 -/
@[reducible]
def f32.f32 := Unit

/-- [core_models::fmt::Arguments]
    Source: 'core-models/src/core/fmt.rs', lines 94:0-94:33
    Visibility: public -/
@[reducible]
def fmt.Arguments := Unit

/-- [core_models::fmt::rt::ArgumentType]
    Source: 'core-models/src/core/fmt.rs', lines 244:4-251:5 -/
@[discriminant isize]
inductive fmt.rt.ArgumentType where
| Placeholder : core.marker.PhantomData Unit → fmt.rt.ArgumentType

/-- [core_models::fmt::rt::Argument]
    Source: 'core-models/src/core/fmt.rs', lines 253:4-255:5
    Visibility: public -/
structure fmt.rt.Argument where
  ty : fmt.rt.ArgumentType

/-- [core_models::fmt::rt::Count]
    Source: 'core-models/src/core/fmt.rs', lines 334:4-338:5 -/
@[discriminant isize]
inductive fmt.rt.Count where
| Is : Std.U16 → fmt.rt.Count
| Param : Std.U16 → fmt.rt.Count
| Implied : fmt.rt.Count

/-- [core_models::fmt::rt::Placeholder]
    Source: 'core-models/src/core/fmt.rs', lines 340:4-345:5 -/
structure fmt.rt.Placeholder where
  position : Std.Usize
  flags : Std.U32
  precision : fmt.rt.Count
  width : fmt.rt.Count

/-- [core_models::fmt::rt::UnsafeArg]
    Source: 'core-models/src/core/fmt.rs', lines 347:4-347:21 -/
@[reducible]
def fmt.rt.UnsafeArg := Unit

/-- Trait declaration: [core_models::hash::Hasher]
    Source: 'core-models/src/core/hash.rs', lines 2:0-7:1
    Visibility: public -/
structure hash.Hasher (Self : Type) where
  finish : Self → RustM Std.U64
  write : Self → Slice Std.U8 → RustM Self

/-- Trait declaration: [core_models::hash::Hash]
    Source: 'core-models/src/core/hash.rs', lines 11:0-16:1
    Visibility: public -/
structure hash.Hash (Self : Type) where
  hash : forall {H : Type} (HasherInst : hash.Hasher H), Self → H → RustM H

/-- [core_models::iter::adapters::fuse::Fuse]
    Source: 'core-models/src/core/iter.rs', lines 1050:8-1053:9
    Visibility: public -/
structure iter.adapters.fuse.Fuse (I : Type) where
  iter : I
  done : Bool

/-- [core_models::iter::adapters::inspect::Inspect]
    Source: 'core-models/src/core/iter.rs', lines 1023:8-1026:9
    Visibility: public -/
structure iter.adapters.inspect.Inspect (I : Type) (F : Type) where
  iter : I
  f : F

/-- [core_models::iter::adapters::map_while::MapWhile]
    Source: 'core-models/src/core/iter.rs', lines 999:8-1002:9
    Visibility: public -/
structure iter.adapters.map_while.MapWhile (I : Type) (F : Type) where
  iter : I
  f : F

/-- [core_models::iter::adapters::skip_while::SkipWhile]
    Source: 'core-models/src/core/iter.rs', lines 962:8-966:9
    Visibility: public -/
structure iter.adapters.skip_while.SkipWhile (I : Type) (P : Type) where
  iter : I
  flag : Bool
  predicate : P

/-- [core_models::iter::adapters::take_while::TakeWhile]
    Source: 'core-models/src/core/iter.rs', lines 922:8-926:9
    Visibility: public -/
structure iter.adapters.take_while.TakeWhile (I : Type) (P : Type) where
  iter : I
  flag : Bool
  predicate : P

/-- [core_models::iter::adapters::filter_map::FilterMap]
    Source: 'core-models/src/core/iter.rs', lines 891:8-894:9
    Visibility: public -/
structure iter.adapters.filter_map.FilterMap (I : Type) (F : Type) where
  iter : I
  f : F

/-- [core_models::iter::adapters::skip::Skip]
    Source: 'core-models/src/core/iter.rs', lines 861:8-864:9
    Visibility: public -/
structure iter.adapters.skip.Skip (I : Type) where
  iter : I
  n : Std.Usize

/-- [core_models::iter::adapters::chain::Chain]
    Source: 'core-models/src/core/iter.rs', lines 828:8-831:9
    Visibility: public -/
structure iter.adapters.chain.Chain (A : Type) (B : Type) where
  a : option.Option A
  b : B

/-- [core_models::iter::adapters::filter::Filter]
    Source: 'core-models/src/core/iter.rs', lines 792:8-795:9
    Visibility: public -/
structure iter.adapters.filter.Filter (I : Type) (P : Type) where
  iter : I
  predicate : P

/-- [core_models::iter::adapters::zip::Zip]
    Source: 'core-models/src/core/iter.rs', lines 763:8-766:9
    Visibility: public -/
structure iter.adapters.zip.Zip (I1 : Type) (I2 : Type) where
  it1 : I1
  it2 : I2

/-- [core_models::iter::adapters::flatten::Flatten]
    Source: 'core-models/src/core/iter.rs', lines 717:8-723:9
    Visibility: public -/
structure iter.adapters.flatten.Flatten (I : Type) (Clause0_Item : Type)
  (Clause1_Item : Type) where
  it : I
  current : option.Option Clause0_Item

/-- [core_models::iter::adapters::flat_map::FlatMap]
    Source: 'core-models/src/core/iter.rs', lines 677:8-681:9
    Visibility: public -/
structure iter.adapters.flat_map.FlatMap (I : Type) (U : Type) (F : Type) where
  it : I
  f : F
  current : option.Option U

/-- [core_models::iter::adapters::take::Take]
    Source: 'core-models/src/core/iter.rs', lines 649:8-652:9
    Visibility: public -/
structure iter.adapters.take.Take (I : Type) where
  iter : I
  n : Std.Usize

/-- [core_models::iter::adapters::map::Map]
    Source: 'core-models/src/core/iter.rs', lines 616:8-619:9
    Visibility: public -/
structure iter.adapters.map.Map (I : Type) (F : Type) where
  iter : I
  f : F

/-- [core_models::iter::adapters::step_by::StepBy]
    Source: 'core-models/src/core/iter.rs', lines 580:8-583:9
    Visibility: public -/
structure iter.adapters.step_by.StepBy (I : Type) where
  iter : I
  step : Std.Usize

/-- [core_models::iter::adapters::enumerate::Enumerate]
    Source: 'core-models/src/core/iter.rs', lines 489:8-492:9
    Visibility: public -/
structure iter.adapters.enumerate.Enumerate (I : Type) where
  iter : I
  count : Std.Usize

/-- Trait declaration: [core_models::iter::traits::collect::FromIterator]
    Source: 'core-models/src/core/iter.rs', lines 472:8-480:9
    Visibility: public -/
structure iter.traits.collect.FromIterator (Self : Type) (A : Type) where
  from_iter : forall {T : Type} {Clause0_IntoIter : Type} (IntoIteratorInst :
    iter.traits.collect.IntoIterator T A Clause0_IntoIter), T → RustM Self

/-- Trait declaration: [core_models::iter::traits::iterator::IteratorMethods]
    Source: 'core-models/src/core/iter.rs', lines 30:8-104:9 -/
structure iter.traits.iterator.IteratorMethods (Self : Type) (Self_Clause0_Item
  : Type) where
  IteratorInst : iter.traits.iterator.Iterator Self Self_Clause0_Item
  fold : forall {B : Type} {F : Type} (coreopsfunctionFnMutPPairPInst :
    core.ops.function.FnMut F (B × Self_Clause0_Item) B), Self → B → F →
    RustM B
  all : forall {F : Type} (coreopsfunctionFnMutPTuplePBoolInst :
    core.ops.function.FnMut F Self_Clause0_Item Bool), Self → F → RustM
    Bool
  map : forall {O : Type} {F : Type} (coreopsfunctionFnMutPTupleFPInst :
    core.ops.function.FnMut F Self_Clause0_Item O), Self → F → RustM
    (iter.adapters.map.Map Self F)
  enumerate : Self → RustM (iter.adapters.enumerate.Enumerate Self)
  step_by : Self → Std.Usize → RustM (iter.adapters.step_by.StepBy Self)
  take : Self → Std.Usize → RustM (iter.adapters.take.Take Self)
  skip : Self → Std.Usize → RustM (iter.adapters.skip.Skip Self)
  filter : forall {P : Type} (coreopsfunctionFnMutPTupleSharedPBoolInst :
    core.ops.function.FnMut P Self_Clause0_Item Bool), Self → P → RustM
    (iter.adapters.filter.Filter Self P)
  filter_map : forall {B : Type} {F : Type}
    (coreopsfunctionFnMutPTupleFOptionInst : core.ops.function.FnMut F
    Self_Clause0_Item (option.Option B)), Self → F → RustM
    (iter.adapters.filter_map.FilterMap Self F)
  take_while : forall {P : Type} (coreopsfunctionFnMutPTupleSharedPBoolInst :
    core.ops.function.FnMut P Self_Clause0_Item Bool), Self → P → RustM
    (iter.adapters.take_while.TakeWhile Self P)
  skip_while : forall {P : Type} (coreopsfunctionFnMutPTupleSharedPBoolInst :
    core.ops.function.FnMut P Self_Clause0_Item Bool), Self → P → RustM
    (iter.adapters.skip_while.SkipWhile Self P)
  map_while : forall {B : Type} {F : Type}
    (coreopsfunctionFnMutPTupleFOptionInst : core.ops.function.FnMut F
    Self_Clause0_Item (option.Option B)), Self → F → RustM
    (iter.adapters.map_while.MapWhile Self F)
  inspect : forall {F : Type} (coreopsfunctionFnMutPTupleSharedPTupleInst :
    core.ops.function.FnMut F Self_Clause0_Item Unit), Self → F → RustM
    (iter.adapters.inspect.Inspect Self F)
  fuse : Self → RustM (iter.adapters.fuse.Fuse Self)
  flat_map : forall {U : Type} {F : Type} {Clause0_Item : Type} (IteratorInst1
    : iter.traits.iterator.Iterator U Clause0_Item)
    (coreopsfunctionFnMutPTupleFPInst : core.ops.function.FnMut F
    Self_Clause0_Item U), Self → F → RustM (iter.adapters.flat_map.FlatMap
    Self U F)
  flatten : forall {Clause0_Item : Type} (IteratorInst1 :
    iter.traits.iterator.Iterator Self_Clause0_Item Clause0_Item), Self →
    RustM (iter.adapters.flatten.Flatten Self Self_Clause0_Item Clause0_Item)
  zip : forall {I2 : Type} {Clause0_Item : Type} (IteratorInst1 :
    iter.traits.iterator.Iterator I2 Clause0_Item), Self → I2 → RustM
    (iter.adapters.zip.Zip Self I2)
  chain : forall {U : Type} (IteratorInst1 : iter.traits.iterator.Iterator U
    Self_Clause0_Item), Self → U → RustM (iter.adapters.chain.Chain Self U)
  any : forall {F : Type} (coreopsfunctionFnMutPTuplePBoolInst :
    core.ops.function.FnMut F Self_Clause0_Item Bool), Self → F → RustM
    Bool
  find : forall {P : Type} (coreopsfunctionFnMutPTupleSharedPBoolInst :
    core.ops.function.FnMut P Self_Clause0_Item Bool), Self → P → RustM
    (option.Option Self_Clause0_Item)
  find_map : forall {B : Type} {F : Type}
    (coreopsfunctionFnMutPTupleFOptionInst : core.ops.function.FnMut F
    Self_Clause0_Item (option.Option B)), Self → F → RustM (option.Option
    B)
  position : forall {P : Type} (coreopsfunctionFnMutPTuplePBoolInst :
    core.ops.function.FnMut P Self_Clause0_Item Bool), Self → P → RustM
    (option.Option Std.Usize)
  count : Self → RustM Std.Usize
  nth : Self → Std.Usize → RustM (option.Option Self_Clause0_Item)
  last : Self → RustM (option.Option Self_Clause0_Item)
  for_each : forall {F : Type} (coreopsfunctionFnMutPTuplePTupleInst :
    core.ops.function.FnMut F Self_Clause0_Item Unit), Self → F → RustM
    Unit
  reduce : forall {F : Type} (coreopsfunctionFnMutPPairPInst :
    core.ops.function.FnMut F (Self_Clause0_Item × Self_Clause0_Item)
    Self_Clause0_Item), Self → F → RustM (option.Option Self_Clause0_Item)
  min : forall (cmpOrdInst : cmp.Ord Self_Clause0_Item), Self → RustM
    (option.Option Self_Clause0_Item)
  max : forall (cmpOrdInst : cmp.Ord Self_Clause0_Item), Self → RustM
    (option.Option Self_Clause0_Item)
  collect : forall {B : Type} (collectFromIteratorInst :
    iter.traits.collect.FromIterator B Self_Clause0_Item), Self → RustM B

/-- Trait declaration: [core_models::iter::traits::double_ended::DoubleEndedIterator]
    Source: 'core-models/src/core/iter.rs', lines 440:8-443:9
    Visibility: public -/
structure iter.traits.double_ended.DoubleEndedIterator (Self : Type)
  (Self_Clause0_Item : Type) where
  iteratorIteratorInst : iter.traits.iterator.Iterator Self Self_Clause0_Item
  next_back : Self → RustM ((option.Option Self_Clause0_Item) × Self)

/-- Trait declaration: [core_models::iter::traits::exact_size::ExactSizeIterator]
    Source: 'core-models/src/core/iter.rs', lines 454:8-457:9
    Visibility: public -/
structure iter.traits.exact_size.ExactSizeIterator (Self : Type)
  (Self_Clause0_Item : Type) where
  iteratorIteratorInst : iter.traits.iterator.Iterator Self Self_Clause0_Item
  len : Self → RustM Std.Usize

/-- [core_models::iter::adapters::rev::Rev]
    Source: 'core-models/src/core/iter.rs', lines 556:8-558:9
    Visibility: public -/
structure iter.adapters.rev.Rev (I : Type) where
  iter : I

/-- Trait declaration: [core_models::iter::range::Step]
    Source: 'core-models/src/core/iter.rs', lines 1087:4-1107:5
    Visibility: public -/
structure iter.range.Step (Self : Type) where
  cloneCloneInst : clone.Clone Self
  corecmpPartialOrdInst : core.cmp.PartialOrd Self Self
  steps_between : Self → Self → RustM (Std.Usize × (option.Option
    Std.Usize))
  forward_checked : Self → Std.Usize → RustM (option.Option Self)
  backward_checked : Self → Std.Usize → RustM (option.Option Self)
  forward : Self → Std.Usize → RustM Self
  forward_unchecked : Self → Std.Usize → RustM Self
  backward : Self → Std.Usize → RustM Self
  backward_unchecked : Self → Std.Usize → RustM Self

/-- Trait declaration: [core_models::marker::Copy]
    Source: 'core-models/src/core/marker.rs', lines 4:0-4:24
    Visibility: public -/
structure marker.Copy (Self : Type) where
  cloneCloneInst : clone.Clone Self

/-- Trait declaration: [core_models::marker::Send]
    Source: 'core-models/src/core/marker.rs', lines 6:0-6:17
    Visibility: public -/
structure marker.Send (Self : Type) where

/-- Trait declaration: [core_models::marker::Sync]
    Source: 'core-models/src/core/marker.rs', lines 8:0-8:17
    Visibility: public -/
structure marker.Sync (Self : Type) where

/-- Trait declaration: [core_models::marker::Sized]
    Source: 'core-models/src/core/marker.rs', lines 10:0-10:18
    Visibility: public -/
structure marker.Sized (Self : Type) where

/-- Trait declaration: [core_models::marker::StructuralPartialEq]
    Source: 'core-models/src/core/marker.rs', lines 12:0-12:32
    Visibility: public -/
structure marker.StructuralPartialEq (Self : Type) where

/-
/-- [core_models::marker::PhantomData]
    Source: 'core-models/src/core/marker.rs', lines 49:0-49:25 -/
@[reducible]
def marker.PhantomData (T : Type) := T
-/  -- replaced by rewrite_phantom_data in favor of the def in `TypesPrologue.lean`

/-- [core_models::mem::manually_drop::ManuallyDrop]
    Source: 'core-models/src/core/mem.rs', lines 136:4-138:5
    Visibility: public -/
structure mem.manually_drop.ManuallyDrop (T : Type) where
  value : T

/-- [core_models::num::error::IntErrorKind]
    Source: 'core-models/src/core/num/error.rs', lines 35:0-35:24
    Visibility: public -/
@[reducible]
def num.error.IntErrorKind := Unit

/-- [core_models::num::error::ParseIntError]
    Source: 'core-models/src/core/num/error.rs', lines 19:0-21:1
    Visibility: public -/
structure num.error.ParseIntError where
  kind : num.error.IntErrorKind

/-- [core_models::num::u8]
    Source: 'core-models/src/core/num/mod.rs', lines 539:0-539:14
    Visibility: public -/
@[reducible]
def num.u8 := Unit

/-- [core_models::num::u16]
    Source: 'core-models/src/core/num/mod.rs', lines 542:0-542:15
    Visibility: public -/
@[reducible]
def num.u16 := Unit

/-- [core_models::num::u32]
    Source: 'core-models/src/core/num/mod.rs', lines 545:0-545:15
    Visibility: public -/
@[reducible]
def num.u32 := Unit

/-- [core_models::num::u64]
    Source: 'core-models/src/core/num/mod.rs', lines 548:0-548:15
    Visibility: public -/
@[reducible]
def num.u64 := Unit

/-- [core_models::num::u128]
    Source: 'core-models/src/core/num/mod.rs', lines 551:0-551:16
    Visibility: public -/
@[reducible]
def num.u128 := Unit

/-- [core_models::num::usize]
    Source: 'core-models/src/core/num/mod.rs', lines 554:0-554:17
    Visibility: public -/
@[reducible]
def num.usize := Unit

/-- [core_models::num::i8]
    Source: 'core-models/src/core/num/mod.rs', lines 557:0-557:14
    Visibility: public -/
@[reducible]
def num.i8 := Unit

/-- [core_models::num::i16]
    Source: 'core-models/src/core/num/mod.rs', lines 560:0-560:15
    Visibility: public -/
@[reducible]
def num.i16 := Unit

/-- [core_models::num::i32]
    Source: 'core-models/src/core/num/mod.rs', lines 563:0-563:15
    Visibility: public -/
@[reducible]
def num.i32 := Unit

/-- [core_models::num::i64]
    Source: 'core-models/src/core/num/mod.rs', lines 566:0-566:15
    Visibility: public -/
@[reducible]
def num.i64 := Unit

/-- [core_models::num::i128]
    Source: 'core-models/src/core/num/mod.rs', lines 569:0-569:16
    Visibility: public -/
@[reducible]
def num.i128 := Unit

/-- [core_models::num::isize]
    Source: 'core-models/src/core/num/mod.rs', lines 572:0-572:17
    Visibility: public -/
@[reducible]
def num.isize := Unit

/-- Trait declaration: [core_models::ops::arith::Add]
    Source: 'core-models/src/core/ops.rs', lines 3:4-6:5
    Visibility: public -/
structure ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type) where
  add : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::Sub]
    Source: 'core-models/src/core/ops.rs', lines 8:4-11:5
    Visibility: public -/
structure ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type) where
  sub : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::Mul]
    Source: 'core-models/src/core/ops.rs', lines 13:4-16:5
    Visibility: public -/
structure ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type) where
  mul : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::Div]
    Source: 'core-models/src/core/ops.rs', lines 18:4-21:5
    Visibility: public -/
structure ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type) where
  div : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::Neg]
    Source: 'core-models/src/core/ops.rs', lines 23:4-26:5
    Visibility: public -/
structure ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::Rem]
    Source: 'core-models/src/core/ops.rs', lines 28:4-31:5
    Visibility: public -/
structure ops.arith.Rem (Self : Type) (Rhs : Type) (Self_Output : Type) where
  rem : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::arith::AddAssign]
    Source: 'core-models/src/core/ops.rs', lines 33:4-35:5
    Visibility: public -/
structure ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::arith::SubAssign]
    Source: 'core-models/src/core/ops.rs', lines 37:4-39:5
    Visibility: public -/
structure ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::arith::MulAssign]
    Source: 'core-models/src/core/ops.rs', lines 41:4-43:5
    Visibility: public -/
structure ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::arith::DivAssign]
    Source: 'core-models/src/core/ops.rs', lines 45:4-47:5
    Visibility: public -/
structure ops.arith.DivAssign (Self : Type) (Rhs : Type) where
  div_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::arith::RemAssign]
    Source: 'core-models/src/core/ops.rs', lines 49:4-51:5
    Visibility: public -/
structure ops.arith.RemAssign (Self : Type) (Rhs : Type) where
  rem_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::bit::Shr]
    Source: 'core-models/src/core/ops.rs', lines 81:4-84:5
    Visibility: public -/
structure ops.bit.Shr (Self : Type) (Rhs : Type) (Self_Output : Type) where
  shr : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::Shl]
    Source: 'core-models/src/core/ops.rs', lines 86:4-89:5
    Visibility: public -/
structure ops.bit.Shl (Self : Type) (Rhs : Type) (Self_Output : Type) where
  shl : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::BitXor]
    Source: 'core-models/src/core/ops.rs', lines 91:4-94:5
    Visibility: public -/
structure ops.bit.BitXor (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitxor : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::BitAnd]
    Source: 'core-models/src/core/ops.rs', lines 96:4-99:5
    Visibility: public -/
structure ops.bit.BitAnd (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitand : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::BitOr]
    Source: 'core-models/src/core/ops.rs', lines 101:4-104:5
    Visibility: public -/
structure ops.bit.BitOr (Self : Type) (Rhs : Type) (Self_Output : Type) where
  bitor : Self → Rhs → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::Not]
    Source: 'core-models/src/core/ops.rs', lines 106:4-109:5
    Visibility: public -/
structure ops.bit.Not (Self : Type) (Self_Output : Type) where
  not : Self → RustM Self_Output

/-- Trait declaration: [core_models::ops::bit::ShrAssign]
    Source: 'core-models/src/core/ops.rs', lines 111:4-113:5
    Visibility: public -/
structure ops.bit.ShrAssign (Self : Type) (Rhs : Type) where
  shr_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::bit::ShlAssign]
    Source: 'core-models/src/core/ops.rs', lines 115:4-117:5
    Visibility: public -/
structure ops.bit.ShlAssign (Self : Type) (Rhs : Type) where
  shl_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::bit::BitXorAssign]
    Source: 'core-models/src/core/ops.rs', lines 119:4-121:5
    Visibility: public -/
structure ops.bit.BitXorAssign (Self : Type) (Rhs : Type) where
  bitxor_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::bit::BitAndAssign]
    Source: 'core-models/src/core/ops.rs', lines 123:4-125:5
    Visibility: public -/
structure ops.bit.BitAndAssign (Self : Type) (Rhs : Type) where
  bitand_assign : Self → Rhs → RustM Self

/-- Trait declaration: [core_models::ops::bit::BitOrAssign]
    Source: 'core-models/src/core/ops.rs', lines 127:4-129:5
    Visibility: public -/
structure ops.bit.BitOrAssign (Self : Type) (Rhs : Type) where
  bitor_assign : Self → Rhs → RustM Self

/-- [core_models::ops::control_flow::ControlFlow]
    Source: 'core-models/src/core/ops.rs', lines 134:4-139:5
    Visibility: public -/
@[discriminant isize]
inductive ops.control_flow.ControlFlow (B : Type) (C : Type) where
| Continue : C → ops.control_flow.ControlFlow B C
| Break : B → ops.control_flow.ControlFlow B C

/-
/-- Trait declaration: [core_models::ops::function::FnOnce]
    Source: 'core-models/src/core/ops.rs', lines 163:4-167:5
    Visibility: public -/
structure ops.function.FnOnce (Self : Type) (Args : Type) (Self_Output : Type)
  where
  call_once : Self → Args → RustM Self_Output
-/

/-
/-- Trait declaration: [core_models::ops::function::FnMut]
    Source: 'core-models/src/core/ops.rs', lines 171:4-174:5
    Visibility: public -/
structure ops.function.FnMut (Self : Type) (Args : Type) (Self_Clause0_Output :
  Type) where
  FnOnceInst : ops.function.FnOnce Self Args Self_Clause0_Output
  call_mut : Self → Args → RustM Self_Clause0_Output
-/

/-
/-- Trait declaration: [core_models::ops::function::Fn]
    Source: 'core-models/src/core/ops.rs', lines 259:4-262:5
    Visibility: public -/
structure ops.function.Fn (Self : Type) (Args : Type)
  (Self_Clause0_Clause0_Output : Type) where
  FnMutInst : ops.function.FnMut Self Args Self_Clause0_Clause0_Output
  call : Self → Args → RustM Self_Clause0_Clause0_Output
-/

/-- Trait declaration: [core_models::ops::try_trait::FromResidual]
    Source: 'core-models/src/core/ops.rs', lines 267:4-269:5
    Visibility: public -/
structure ops.try_trait.FromResidual (Self : Type) (R : Type) where
  from_residual : R → RustM Self

/-- Trait declaration: [core_models::ops::try_trait::Try]
    Source: 'core-models/src/core/ops.rs', lines 272:4-277:5
    Visibility: public -/
structure ops.try_trait.Try (Self : Type) (Self_Output : Type) (Self_Residual :
  Type) where
  from_output : Self_Output → RustM Self
  branch : Self → RustM (ops.control_flow.ControlFlow Self_Residual
    Self_Output)

/-- Trait declaration: [core_models::ops::deref::Deref]
    Source: 'core-models/src/core/ops.rs', lines 282:4-286:5
    Visibility: public -/
structure ops.deref.Deref (Self : Type) (Self_Target : Type) where
  deref : Self → RustM Self_Target

/-- Trait declaration: [core_models::ops::deref::DerefMut]
    Source: 'core-models/src/core/ops.rs', lines 300:4-302:5
    Visibility: public -/
structure ops.deref.DerefMut (Self : Type) (Self_Clause0_Target : Type) where
  DerefInst : ops.deref.Deref Self Self_Clause0_Target
  deref_mut : Self → RustM (Self_Clause0_Target × (Self_Clause0_Target →
    Self))

/-- Trait declaration: [core_models::ops::drop::Drop]
    Source: 'core-models/src/core/ops.rs', lines 307:4-313:5
    Visibility: public -/
structure ops.drop.Drop (Self : Type) where
  drop : Self → RustM Self

/-- [core_models::ops::range::RangeTo]
    Source: 'core-models/src/core/ops.rs', lines 318:4-320:5
    Visibility: public -/
structure ops.range.RangeTo (T : Type) where
  «end» : T

/-- [core_models::ops::range::RangeFrom]
    Source: 'core-models/src/core/ops.rs', lines 322:4-324:5
    Visibility: public -/
structure ops.range.RangeFrom (T : Type) where
  start : T

/-- [core_models::ops::range::Range]
    Source: 'core-models/src/core/ops.rs', lines 326:4-329:5
    Visibility: public -/
structure ops.range.Range (T : Type) where
  start : T
  «end» : T

/-- [core_models::ops::range::RangeFull]
    Source: 'core-models/src/core/ops.rs', lines 331:4-331:25
    Visibility: public -/
@[reducible]
def ops.range.RangeFull := Unit

/-- [core_models::ops::range::RangeInclusive]
    Source: 'core-models/src/core/ops.rs', lines 333:4-336:5
    Visibility: public -/
structure ops.range.RangeInclusive (T : Type) where
  start : T
  «end» : T

/-- [core_models::panic::location::Location]
    Source: 'core-models/src/core/panic.rs', lines 11:4-15:5
    Visibility: public -/
structure panic.location.Location where
  filename : Str
  line : Std.U32
  col : Std.U32

/-- [core_models::panic::panic_info::PanicInfo]
    Source: 'core-models/src/core/panic.rs', lines 21:4-26:5
    Visibility: public -/
structure panic.panic_info.PanicInfo where
  message : fmt.Arguments
  location : panic.location.Location
  can_unwind : Bool
  force_no_backtrace : Bool

/-- [core_models::panicking::AssertKind]
    Source: 'core-models/src/core/panicking.rs', lines 24:0-31:1
    Visibility: public -/
@[discriminant isize]
inductive panicking.AssertKind where
| Eq : panicking.AssertKind
| Ne : panicking.AssertKind
| Match : panicking.AssertKind

/-- [core_models::pin::Pin]
    Source: 'core-models/src/core/pin.rs', lines 6:0-8:1
    Visibility: public -/
structure pin.Pin (Ptr : Type) where
  pointer : Ptr

/-- [core_models::pin::helper::PinHelper]
    Source: 'core-models/src/core/pin.rs', lines 14:4-16:5
    Visibility: public -/
structure pin.helper.PinHelper (Ptr : Type) where
  pointer : Ptr

/-- [core_models::result::SeqIter]
    Source: 'core-models/src/core/result.rs', lines 353:0-353:53 -/
@[reducible]
def result.SeqIter (A : Type) := rust_primitives.sequence.Seq A

/-
/-- [core_models::slice::Slice]
    Source: 'core-models/src/core/slice.rs', lines 7:0-7:21 -/
@[reducible]
def slice.Slice (T : Type) := Slice T
-/

/-- [core_models::slice::iter::Chunks]
    Source: 'core-models/src/core/slice.rs', lines 14:4-17:5
    Visibility: public -/
structure slice.iter.Chunks (T : Type) where
  cs : Std.Usize
  elements : Slice T

/-- [core_models::slice::iter::ChunksExact]
    Source: 'core-models/src/core/slice.rs', lines 24:4-27:5
    Visibility: public -/
structure slice.iter.ChunksExact (T : Type) where
  cs : Std.Usize
  elements : Slice T

/-- [core_models::slice::iter::Iter]
    Source: 'core-models/src/core/slice.rs', lines 34:4-34:43
    Visibility: public -/
@[reducible]
def slice.iter.Iter (T : Type) := rust_primitives.sequence.Seq T

/-- [core_models::slice::iter::IterMut]
    Source: 'core-models/src/core/slice.rs', lines 43:4-43:50
    Visibility: public -/
@[reducible]
def slice.iter.IterMut (T : Type) := rust_primitives.sequence.Seq T

/-- [core_models::slice::iter::Windows]
    Source: 'core-models/src/core/slice.rs', lines 124:4-127:5
    Visibility: public -/
structure slice.iter.Windows (T : Type) where
  size : Std.Usize
  elements : Slice T

/-- Trait declaration: [core_models::slice::index::SliceIndex]
    Source: 'core-models/src/core/slice.rs', lines 506:4-531:5
    Visibility: public -/
structure slice.index.SliceIndex (Self : Type) (T : Type) (Self_Output : Type)
  where
  get : Self → T → RustM (option.Option Self_Output)
  index : Self → T → RustM Self_Output
  get_unchecked : Self → T → RustM Self_Output
  get_mut : Self → T → RustM ((option.Option Self_Output) × (option.Option
    Self_Output → T))
  get_unchecked_mut : Self → T → RustM (Self_Output × (Self_Output → T))
  index_mut : Self → T → RustM (Self_Output × (Self_Output → T))

/-- [core_models::str::error::Utf8Error]
    Source: 'core-models/src/core/str.rs', lines 40:4-40:25
    Visibility: public -/
@[reducible]
def str.error.Utf8Error := Unit

/-- [core_models::str::iter::Split]
    Source: 'core-models/src/core/str.rs', lines 53:4-53:23 -/
@[reducible]
def str.iter.Split (T : Type) := T

/-- Trait declaration: [core_models::str::traits::FromStr]
    Source: 'core-models/src/core/str.rs', lines 57:4-60:5 -/
structure str.traits.FromStr (Self : Type) (Self_Err : Type) where
  from_str : Str → RustM (result.Result Self Self_Err)

/-- [core_models::sync::atomic::AtomicBool]
    Source: 'core-models/src/core/sync.rs', lines 11:4-13:5
    Visibility: public -/
structure sync.atomic.AtomicBool where
  v : Std.U8

/-- [core_models::sync::atomic::AtomicU32]
    Source: 'core-models/src/core/sync.rs', lines 16:4-18:5
    Visibility: public -/
structure sync.atomic.AtomicU32 where
  v : Std.U32

end CoreModels.core
